#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class BallsSeparating {
public:
	int minOperations(vector <int> red, vector <int> green, vector <int> blue) {
		vector< pair<int, pair<int, int> > > a;
		vector<int> A[3];
		
		A[0] = red;
		A[1] = green;
		A[2] = blue;
		int suma = 0, sumb = 0, sumc = 0;
		
		for (int i = 0; i < red.size(); ++i) {
			a.push_back(make_pair(red[i], make_pair(0, i)));
			suma += red[i];
		}
		for (int i = 0; i < green.size(); ++i) {
			a.push_back(make_pair(green[i], make_pair(1, i)));
			sumb += green[i];
		}
		for (int i = 0; i < blue.size(); ++i) {
			a.push_back(make_pair(blue[i], make_pair(2, i)));
			sumc += blue[i];
		}
		
		sort(a.begin(), a.end());
		
		int ans = 0, free = red.size();
		vector<int> c(a.size(), -1);
		bool any[3];
		any[0] = any[1] = any[2] = 0;
		
		while (a.size() > 0) {
//			for (int i = 0; i < a.size(); ++i) cerr << a[i].first << "," << a[i].second.first << "," << a[i].second.second << " ";
//			cerr << endl;
		
			pair<int, pair<int, int> > p = a[a.size() - 1];
			int pos = p.second.second;
			int col = p.second.first;
			
			bool t = any[col];
			any[col] = true;
			if (!any[0] + !any[1] + !any[2] > free - 1) {
				any[col] = t;
				
//				cerr << any[0] << " " << any[1] << " " << any[2] << " " << free << endl;
				if (any[col]) {	
					ans += a[a.size() - 1].first;
//					cerr << "ans2: " << ans << endl;
					a.erase(  a.begin() + a.size() - 1 );
				} else
					return -1;
				continue;				
			}			
			any[col] = t;
//			cerr << col << endl;
			a.erase( find(a.begin(), a.end(), p) );
			c[pos] = col;
			any[col] = true;
			--free;
			for (int i = 0; i < 3; ++i) if (i != col) {
				vector< pair<int, pair<int, int> > >::iterator it = find(a.begin(), a.end(), make_pair(A[i][pos], make_pair(i, pos)));
				if (it != a.end()) {
					a.erase(it);
					ans += A[i][pos];
//					cerr << "ans: " << ans << endl;
				}
			}			
		}
		
		return ans;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <int> p0, vector <int> p1, vector <int> p2, bool hasAnswer, int p3) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p2[i];
	}
	cout << "}";
	cout << "]" << endl;
	BallsSeparating *obj;
	int answer;
	obj = new BallsSeparating();
	clock_t startTime = clock();
	answer = obj->minOperations(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p3 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p3;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	vector <int> p1;
	vector <int> p2;
	int p3;

    {
	// ----- test 0 -----
	int t0[] = {10,9,9,9};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {9,1,1,1};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {9,1,1,1};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 33;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}

	
	{
	// ----- test 0 -----
	int t0[] = {1,1,1};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {1,1,1};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {1,1,1};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 6;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {5};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {6};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {8};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = -1;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {4,6,5,7};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {7,4,6,3};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {6,5,3,8};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 37;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	int t0[] = {7,12,9,9,7};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {7,10,8,8,9};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {8,9,5,6,13};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 77;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	int t0[] = {842398,491273,958925,849859,771363,67803,184892,391907,256150,75799};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {268944,342402,894352,228640,903885,908656,414271,292588,852057,889141};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {662939,340220,600081,390298,376707,372199,435097,40266,145590,505103};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 7230607;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
